### ISSUE TITLE
Downloading the block chain extremely slow

### ISSUE THREAD

**Issue by bjackson** [lian/bitcoin-ruby#42]
Importing the blockchain from a file seems to be about as slow. It seems to only get a few blocks per minute, is this to be expected? Any chances of a speedup in coming releases?

**Comment by mhanne** [comment]
Thanks everybody for contributing to this! I'm going to close this issue because there have been several topics mixed up in here by now, and the relevant part of the project has moved to https://github.com/mhanne/bitcoin-ruby-blockchain. In the meantime, there have been some massive performance improvements, and I think most of the concrete issues in this thread have been addressed.
But feel free to create new issues :)
